In [16]:
import pandas as pd
from datetime import datetime
import numpy as np

In [1]:
path = "/content/"  # THIS LINE NEEDS TO BE CHANGED BASED ON THE PATH OF THE FILES TO RETRIEVE

# Import needed CSV for the dataset inlducing cases for day for fips
final_2020 = pd.read_csv(f"{path}final_df_2020.csv")
final_2021 = pd.read_csv(f"{path}final_df_2021.csv")
final_2022 = pd.read_csv(f"{path}final_df_2022.csv")

# Extrate information from dataframe and create a new dataframe with
# column = FIPS and row = Cases per Date
db = {}
for index, row in final_2020.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']
for index, row in final_2021.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']
for index, row in final_2022.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']

df_cases = pd.DataFrame(db.values(), index=pd.MultiIndex.from_tuples(db.keys())).unstack(1).fillna(0)[0]

In [3]:
df_cases

1001     1003    1005    1007     1009    1011    1013   \
2020-01-21      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-22      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-23      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-24      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-25      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
...             ...      ...     ...     ...      ...     ...     ...   
2022-04-07  15742.0  55468.0  5658.0  6421.0  14926.0  2304.0  5052.0   
2022-04-08  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-09  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-10  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-11  15747.0  55499.0  5658.0  6425.0  14934.0  2303.0  5052.0   

              1015    1017    1019   ...   72141   72143    72145  72147  \
2020-01-21      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-22      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-23      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-24      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-25      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
...             ...     ...     ...  ...     ...     ...      ...    ...   
2022-04-07  32355.0  8471.0  5114.0  ...  3322.0  6110.0  10231.0  713.0   
2022-04-08  32355.0  8471.0  5115.0  ...  3329.0  6115.0  10239.0  713.0   
2022-04-09  32355.0  8471.0  5115.0  ...  3333.0  6120.0  10242.0  713.0   
2022-04-10  32355.0  8471.0  5115.0  ...  3336.0  6129.0  10272.0  713.0   
2022-04-11  32359.0  8474.0  5116.0  ...  3337.0  6135.0  10275.0  713.0   

             72149   72151   72153   78010  78020   78030  
2020-01-21     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-22     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-23     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-24     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-25     0.0     0.0     0.0     0.0    0.0     0.0  
...            ...     ...     ...     ...    ...     ...  
2022-04-07  2965.0  4284.0  4238.0  7751.0  783.0  7206.0  
2022-04-08  2968.0  4294.0  4240.0  7759.0  786.0  7219.0  
2022-04-09  2972.0  4309.0  4240.0  7759.0  786.0  7219.0  
2022-04-10  2983.0  4322.0  4257.0  7759.0  786.0  7219.0  
2022-04-11  2983.0  4329.0  4263.0  7759.0  786.0  7219.0  

[812 rows x 3220 columns]

In [4]:
cases = df_cases.to_numpy()
cases

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [5]:
cases.shape

(812, 3220)

In [33]:
# evaluate the historical average for each node
means_nodes = np.mean(cases, axis=0)
means_nodes

array([ 5806.17241379, 19894.26970443,  2074.64285714, ...,
        1875.92118227,   222.54064039,  2074.22413793])

In [34]:
means_nodes.shape 

(3220,)

In [35]:
HA = np.array([means_nodes.transpose(),]*812)
HA

array([[ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793],
       [ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793],
       [ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793],
       ...,
       [ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793],
       [ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793],
       [ 5806.17241379, 19894.26970443,  2074.64285714, ...,
         1875.92118227,   222.54064039,  2074.22413793]])

In [36]:
HA.shape 

(812, 3220)

In [55]:
from sklearn.metrics import mean_absolute_percentage_error

n = cases.shape[0]*cases.shape[1]

def mape(y_hat, y):
    return 100 * np.abs((y - y_hat) / (y + 5e-8)).mean()

def mape1(y_hat, y, n):
  return 100/n *np.sum((np.abs((y - y_hat)/(y + 5e-8))))

def mae(y_hat, y):
  return np.abs(y - y_hat).mean()


In [56]:
mape(cases, HA)

73.87800514666064

In [57]:
# "{:.5f}".format(mape(cases, HA))

In [58]:
mape1(cases, HA, n)

73.87800514666066

In [59]:
mae(cases, HA)

5970.455350841652