In [1]:
import pandas as pd
from datetime import datetime

path = "/content/"  # THIS LINE NEEDS TO BE CHANGED BASED ON THE PATH OF THE FILES TO RETRIEVE

# Import needed CSV for the dataset inlducing cases for day for fips
final_2020 = pd.read_csv(f"{path}final_df_2020.csv")
final_2021 = pd.read_csv(f"{path}final_df_2021.csv")
final_2022 = pd.read_csv(f"{path}final_df_2022.csv")

# Extrate information from dataframe and create a new dataframe with
# column = FIPS and row = Cases per Date
db = {}
for index, row in final_2020.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']
for index, row in final_2021.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']
for index, row in final_2022.iterrows():
  date = datetime.strptime(row['Date'], '%Y-%m-%d')
  db[(date, (row['FIPS']))] = row['Cases']

df_cases = pd.DataFrame(db.values(), index=pd.MultiIndex.from_tuples(db.keys())).unstack(1).fillna(0)[0]

In [2]:
df_cases

1001     1003    1005    1007     1009    1011    1013   \
2020-01-21      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-22      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-23      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-24      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
2020-01-25      0.0      0.0     0.0     0.0      0.0     0.0     0.0   
...             ...      ...     ...     ...      ...     ...     ...   
2022-04-07  15742.0  55468.0  5658.0  6421.0  14926.0  2304.0  5052.0   
2022-04-08  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-09  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-10  15744.0  55489.0  5658.0  6422.0  14929.0  2304.0  5052.0   
2022-04-11  15747.0  55499.0  5658.0  6425.0  14934.0  2303.0  5052.0   

              1015    1017    1019   ...   72141   72143    72145  72147  \
2020-01-21      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-22      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-23      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-24      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
2020-01-25      0.0     0.0     0.0  ...     0.0     0.0      0.0    0.0   
...             ...     ...     ...  ...     ...     ...      ...    ...   
2022-04-07  32355.0  8471.0  5114.0  ...  3322.0  6110.0  10231.0  713.0   
2022-04-08  32355.0  8471.0  5115.0  ...  3329.0  6115.0  10239.0  713.0   
2022-04-09  32355.0  8471.0  5115.0  ...  3333.0  6120.0  10242.0  713.0   
2022-04-10  32355.0  8471.0  5115.0  ...  3336.0  6129.0  10272.0  713.0   
2022-04-11  32359.0  8474.0  5116.0  ...  3337.0  6135.0  10275.0  713.0   

             72149   72151   72153   78010  78020   78030  
2020-01-21     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-22     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-23     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-24     0.0     0.0     0.0     0.0    0.0     0.0  
2020-01-25     0.0     0.0     0.0     0.0    0.0     0.0  
...            ...     ...     ...     ...    ...     ...  
2022-04-07  2965.0  4284.0  4238.0  7751.0  783.0  7206.0  
2022-04-08  2968.0  4294.0  4240.0  7759.0  786.0  7219.0  
2022-04-09  2972.0  4309.0  4240.0  7759.0  786.0  7219.0  
2022-04-10  2983.0  4322.0  4257.0  7759.0  786.0  7219.0  
2022-04-11  2983.0  4329.0  4263.0  7759.0  786.0  7219.0  

[812 rows x 3220 columns]

In [3]:
cases = df_cases.to_numpy()
cases

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [4]:
cases.shape

(812, 3220)

In [5]:
cases[1:,:] # cases

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [6]:
cases[:-1,:] # previous days 

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.]])

In [7]:
# PREVIOUS CASES: the difference of cases between a day and the next is zero. 
# We predict to have the same number of cases in t w.r.t. t-1
real_cases    = cases[1:,:]
prev_day_pred = cases[:-1,:]

In [8]:
real_cases

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [9]:
prev_day_pred

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.]])

In [10]:
prev_day_pred.shape

(811, 3220)

In [11]:
real_cases.shape

(811, 3220)

In [19]:
from sklearn.metrics import mean_absolute_percentage_error

n = real_cases.shape[0]*real_cases.shape[1]

def mape(y_hat, y):
    return 100 * np.abs((y - y_hat) / (y + 5e-8)).mean()

def mape1(y_hat, y, n):
  return 100/n *np.sum((np.abs((y - y_hat)/(y + 5e-8))))

def mae(y_hat, y):
  return np.abs(y - y_hat).mean()

In [20]:
mape(prev_day_pred, real_cases)

12255.0133334102

In [21]:
mape1(prev_day_pred, real_cases, n)

12255.013333410201

In [23]:
mae(prev_day_pred, real_cases)

29.941452543060862

In [24]:
# PREVIOUS DELTA: we predict that the delta in the number of cases will be the same as the delta from the previous day. 
cur_day  = cases[1:,:]
prev_day = cases[:-1,:]
delta = cur_day - prev_day

In [25]:
cases

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [26]:
cur_day

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [27]:
prev_day

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.]])

In [28]:
delta

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 3., 10.,  0., ...,  0.,  0.,  0.]])

In [29]:
next_day_pred = cur_day + delta
next_day_pred = next_day_pred[:-1,:]
next_day_pred

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15746., 55510.,  5658., ...,  7767.,   789.,  7232.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.]])

In [30]:
next_day_pred.shape

(810, 3220)

In [31]:
true_val = cur_day[1:, :]
true_val

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ...,
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15744., 55489.,  5658., ...,  7759.,   786.,  7219.],
       [15747., 55499.,  5658., ...,  7759.,   786.,  7219.]])

In [32]:
true_val.shape

(810, 3220)

In [33]:
mape(next_day_pred, true_val)

24539.34807289529

In [35]:
mape1(next_day_pred, true_val, 810*3220)

24539.348072895285

In [36]:
mae(next_day_pred, true_val)

25.033098305344684